# Generated by Django 4.2.4 on 2023-08-31 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_details',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='patient_details',
            name='pincode',
        ),
        migrations.AddField(
            model_name='patient_details',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.location'),
        ),
    ]
