# Generated by Django 4.2.4 on 2023-08-31 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_patient_details_dob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_details',
            old_name='conatct',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='patient_details',
            name='pno',
        ),
    ]
