# Generated by Django 4.2.2 on 2023-08-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_conatct_patient_details_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_report',
            name='file_path',
        ),
        migrations.AddField(
            model_name='patient_report',
            name='image',
            field=models.ImageField(null=True, upload_to='skin_images'),
        ),
    ]
