# Generated by Django 4.2.2 on 2023-08-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_patient_report_file_path_patient_report_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_report',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
